name: Build and deploy documentation

on:
  push:
    # all branches
    paths:
      - 'doc/**'

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

# https://github.com/JamesIves/github-pages-deploy-action#readme
permissions:
    contents: write

# Set DYLAN environment variable to GITHUB_WORKSPACE so packages are
# installed in ../../_packages relative to documentation's Makefile
env:
  DYLAN: ${{ github.workspace }}

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build docs with Furo theme
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/fraya/dylan-docs
          options: -v ${{ github.workspace }}/doc:/docs
          run: make html

      - name: Upload html artifact
        uses: actions/upload-artifact@v6
        with:
          name: dylan-gsl-doc-html
          path: doc/build/html/

      - name: Bypassing Jekyll on GH Pages
        run: sudo touch doc/build/html/.nojekyll

      - name: Deploy documents to GH pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc/build/html
